CREATE TYPE "ProductCategory" AS ENUM ('CERAMIC_TILE','PORCELAIN_TILE','MOSAIC_TILE');
CREATE TYPE "ProductColor" AS ENUM ('WHITE','BLACK','GRAY','BEIGE','BROWN','RED','BLUE','GREEN','YELLOW','MULTICOLOR','OTHER');
CREATE TYPE "ProductMaterial" AS ENUM ('CERAMIC','PORCELAIN','GLASS','NATURAL_STONE','MIXED');
CREATE TYPE "ProductFinish" AS ENUM ('MATTE','POLISHED','GLOSSY','SATIN','TEXTURED','OTHER');
CREATE TYPE "ProductSuitability" AS ENUM ('INDOOR','OUTDOOR','BOTH');
CREATE TYPE "UnitOfSale" AS ENUM ('SQUARE_METER','PIECE','BOX');
CREATE TYPE "Currency" AS ENUM ('IRR','TOMAN','USD');
CREATE TABLE "Product" ("id" uuid PRIMARY KEY, "name" varchar(150) NOT NULL, "sku" varchar(64) NOT NULL, "skuNormalized" varchar(64) NOT NULL UNIQUE, "category" "ProductCategory" NOT NULL, "brand" varchar(100), "collection" varchar(100), "color" "ProductColor" NOT NULL, "material" "ProductMaterial" NOT NULL, "widthMm" numeric(12,2) NOT NULL, "heightMm" numeric(12,2) NOT NULL, "thicknessMm" numeric(12,2), "finish" "ProductFinish" NOT NULL, "texture" varchar(40), "floorCompatible" boolean NOT NULL, "wallCompatible" boolean NOT NULL, "suitability" "ProductSuitability" NOT NULL, "slipResistance" varchar(100), "rectified" boolean NOT NULL, "countryOfOrigin" varchar(2), "basePrice" numeric(24,2), "baseCurrency" "Currency", "stockQuantity" numeric(24,3), "unitOfSale" "UnitOfSale" NOT NULL, "description" varchar(5000), "active" boolean NOT NULL DEFAULT false, "archivedAt" timestamptz, "revision" integer NOT NULL DEFAULT 0, "everVisualized" boolean NOT NULL DEFAULT false, "createdById" uuid NOT NULL REFERENCES "User"("id"), "updatedById" uuid NOT NULL REFERENCES "User"("id"), "createdAt" timestamptz NOT NULL DEFAULT now(), "updatedAt" timestamptz NOT NULL DEFAULT now(), CHECK ("floorCompatible" OR "wallCompatible"));
CREATE INDEX "Product_active_archivedAt_category_idx" ON "Product"("active","archivedAt","category"); CREATE INDEX "Product_name_sku_idx" ON "Product"("name","sku");
