import type { PrismaClient } from "@prisma/client";
export type CatalogActor = { id: string; role: "SUPER_ADMIN" | "ADMIN" | "PRODUCT_MANAGER" | "USER" };
export type ProductInput = Record<string, unknown>;
const canEdit = (role: CatalogActor["role"]) => ["SUPER_ADMIN", "ADMIN", "PRODUCT_MANAGER"].includes(role);
const normalize = (value: unknown) => String(value ?? "").trim().toLowerCase();
export class ProductService {
  constructor(private readonly prisma: PrismaClient) {}
  private authority(actor: CatalogActor) { if (!canEdit(actor.role)) throw new Error("FORBIDDEN"); }
  async list(actor: CatalogActor) { const where = actor.role === "USER" ? { active: true, archivedAt: null } : {}; return this.prisma.product.findMany({ where, orderBy: [{ name: "asc" }, { sku: "asc" }], take: 100 }); }
  async get(actor: CatalogActor, id: string) { const product = await this.prisma.product.findUnique({ where: { id } }); if (!product || (actor.role === "USER" && (!product.active || product.archivedAt))) throw new Error("RECORD_NOT_FOUND"); return product; }
  async create(actor: CatalogActor, input: ProductInput) { this.authority(actor); const sku = String(input.sku).trim(); if (!sku || !input.name || !input.floorCompatible && !input.wallCompatible) throw new Error("PRODUCT_INVALID"); const skuNormalized = normalize(sku); const exists = await this.prisma.product.findUnique({ where: { skuNormalized } }); if (exists) throw new Error("SKU_TAKEN"); return this.prisma.product.create({ data: { ...(input as object), sku, skuNormalized, active: false, createdById: actor.id, updatedById: actor.id } as never }); }
  async update(actor: CatalogActor, id: string, input: ProductInput, revision?: number) { this.authority(actor); if (revision === undefined) throw new Error("REVISION_REQUIRED"); const existing = await this.get(actor, id); if (existing.archivedAt) throw new Error("PRODUCT_ARCHIVED"); const changed = await this.prisma.product.updateMany({ where: { id, revision }, data: { ...(input as object), updatedById: actor.id, revision: { increment: 1 } } as never }); if (!changed.count) throw new Error("REVISION_CONFLICT"); return this.get(actor, id); }
  async archive(actor: CatalogActor, id: string, revision?: number) { if (actor.role !== "SUPER_ADMIN" && actor.role !== "ADMIN") throw new Error("FORBIDDEN"); if (revision === undefined) throw new Error("REVISION_REQUIRED"); const changed = await this.prisma.product.updateMany({ where: { id, revision }, data: { archivedAt: new Date(), active: false, revision: { increment: 1 }, updatedById: actor.id } }); if (!changed.count) throw new Error("REVISION_CONFLICT"); return this.get(actor, id); }
  async restore(actor: CatalogActor, id: string, revision?: number) { if (actor.role !== "SUPER_ADMIN" && actor.role !== "ADMIN") throw new Error("FORBIDDEN"); if (revision === undefined) throw new Error("REVISION_REQUIRED"); const changed = await this.prisma.product.updateMany({ where: { id, revision }, data: { archivedAt: null, active: false, revision: { increment: 1 }, updatedById: actor.id } }); if (!changed.count) throw new Error("REVISION_CONFLICT"); return this.get(actor, id); }
  async remove(actor: CatalogActor, id: string, revision?: number) { if (actor.role !== "SUPER_ADMIN" && actor.role !== "ADMIN") throw new Error("FORBIDDEN"); if (revision === undefined) throw new Error("REVISION_REQUIRED"); const product = await this.get(actor, id); if (product.everVisualized) throw new Error("PRODUCT_USED"); const removed = await this.prisma.product.deleteMany({ where: { id, revision } }); if (!removed.count) throw new Error("REVISION_CONFLICT"); }
}
