"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { ApiClientError, apiFetch } from "../../lib/api/client";
import { Status } from "../../components/status";
import { useLocale } from "../../i18n/provider";
type Mode = "login" | "register" | "forgot" | "reset";
const copy = { en: { name: "Name", email: "Email", password: "Password", token: "Reset token", submit: "Continue", pending: "Your account is awaiting administrator approval.", approved: "Signed in successfully.", reset: "Password updated. Please sign in.", forgot: "If an account exists, recovery instructions will be sent.", error: "We could not complete that request.", loading: "Submitting…" }, fa: { name: "نام", email: "ایمیل", password: "رمز عبور", token: "توکن بازیابی", submit: "ادامه", pending: "حساب شما در انتظار تأیید مدیر است.", approved: "ورود با موفقیت انجام شد.", reset: "رمز عبور تغییر کرد. لطفاً وارد شوید.", forgot: "اگر حسابی وجود داشته باشد، دستور بازیابی ارسال می‌شود.", error: "درخواست انجام نشد.", loading: "در حال ارسال…" } } as const;
export function AuthForm({ mode, initialToken = "" }: { mode: Mode; initialToken?: string }) { const { locale } = useLocale(); const router = useRouter(); const text = copy[locale]; const [message, setMessage] = useState<string>(); const [busy, setBusy] = useState(false); async function submit(form: FormData) { setBusy(true); setMessage(undefined); try { if (mode === "register") { await apiFetch("/auth/register", { method: "POST", body: JSON.stringify({ displayName: form.get("displayName"), email: form.get("email"), password: form.get("password"), passwordConfirmation: form.get("passwordConfirmation"), locale }), headers: { "Content-Type": "application/json" } }); setMessage(text.pending); } else if (mode === "login") { const response = await apiFetch<{ access: "APPROVED" | "PENDING" | "REJECTED" | "DISABLED" }>("/auth/login", { method: "POST", body: JSON.stringify({ email: form.get("email"), password: form.get("password") }), headers: { "Content-Type": "application/json" } }); setMessage(response.access === "APPROVED" ? text.approved : text.pending); if (response.access === "APPROVED") router.replace("/dashboard"); } else if (mode === "forgot") { await apiFetch("/auth/password-reset", { method: "POST", body: JSON.stringify({ email: form.get("email") }), headers: { "Content-Type": "application/json" } }); setMessage(text.forgot); } else { await apiFetch("/auth/password-reset/consume", { method: "POST", body: JSON.stringify({ token: form.get("token"), password: form.get("password"), passwordConfirmation: form.get("passwordConfirmation") }), headers: { "Content-Type": "application/json" } }); setMessage(text.reset); } } catch (error) { setMessage(error instanceof ApiClientError ? text.error : text.error); } finally { setBusy(false); } }
return <form action={submit} aria-busy={busy}>{mode === "register" && <label>{text.name}<input name="displayName" autoComplete="name" required maxLength={100} /></label>}{mode === "reset" && <label>{text.token}<input name="token" type="password" defaultValue={initialToken} required autoComplete="one-time-code" /></label>}{mode !== "reset" && <label>{text.email}<input name="email" type="email" autoComplete="email" required /></label>}{mode !== "forgot" && <label>{text.password}<input name="password" type="password" autoComplete={mode === "login" ? "current-password" : "new-password"} minLength={12} maxLength={128} required /></label>}{(mode === "register" || mode === "reset") && <label>{text.password}<input name="passwordConfirmation" type="password" autoComplete="new-password" minLength={12} maxLength={128} required /></label>}<button type="submit" disabled={busy}>{busy ? text.loading : text.submit}</button>{message && <Status>{message}</Status>}</form>; }
